# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-28 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('esp_id', models.AutoField(primary_key=True, serialize=False)),
                ('desc_esp', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
                'db_table': 'especialidad',
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('profesion_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Profesiones',
                'db_table': 'profesion',
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('prof_id', models.AutoField(primary_key=True, serialize=False)),
                ('persona', models.OneToOneField(db_column='per_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='profesionales', to='persona.Persona')),
                ('nro_matricula', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'verbose_name_plural': 'Profesionales',
                'db_table': 'profesional',
                'permissions': (('manage_profesional', 'Can manage profesional'), ('view_profesional', 'Can view profesional'), ('readonly_profesional', 'Can view profesional readonly')),
            },
            bases=('persona.persona',),
        ),
        migrations.CreateModel(
            name='ProfesionalClasif',
            fields=[
                ('prof_clasif_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'profesional_clasif',
            },
        ),
        migrations.CreateModel(
            name='ProfesionalMatricula',
            fields=[
                ('prof_mat_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('N', 'Nacional'), ('P', 'Provincial')], max_length=1)),
                ('matricula', models.CharField(max_length=20)),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de matriculación')),
                ('especialidad', models.ForeignKey(db_column='esp_id', on_delete=django.db.models.deletion.PROTECT, to='profesionales.Especialidad')),
                ('profesion', models.ForeignKey(blank=True, db_column='profesion_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='profesionales.Profesion')),
                ('profesional', models.ForeignKey(db_column='prof_id', on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='profesionales.Profesional')),
            ],
            options={
                'db_table': 'profesional_matricula',
            },
        ),
        migrations.AddField(
            model_name='profesional',
            name='clasificacion',
            field=models.ForeignKey(blank=True, db_column='prof_clasif_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesionales', to='profesionales.ProfesionalClasif'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='especialidad',
            field=models.ForeignKey(blank=True, db_column='esp_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesionales', to='profesionales.Especialidad'),
        ),
    ]
