# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 15:27
from __future__ import unicode_literals

import apps.core.db.metadata
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alfabetizacion',
            fields=[
                ('alfab_id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_alfab', models.CharField(blank=True, max_length=2, null=True)),
                ('nivel', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Alfabetizacion',
                'db_table': 'alfabetizacion',
            },
        ),
        migrations.CreateModel(
            name='CondIva',
            fields=[
                ('cond_iva_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Condición frente a IVA',
                'db_table': 'cond_iva',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_dep', models.CharField(max_length=3)),
                ('desc_dep', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='DiabetesTipo',
            fields=[
                ('diab_tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('diab_tipo_descr', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Tipos de diabetes',
                'db_table': 'diabetes_tipo',
            },
        ),
        migrations.CreateModel(
            name='DocClase',
            fields=[
                ('doc_clase_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('cod_doc_clase', models.CharField(blank=True, max_length=1, null=True)),
                ('desc_doc_clase', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Clases de Documentos',
                'db_table': 'doc_clase',
            },
        ),
        migrations.CreateModel(
            name='DocTipo',
            fields=[
                ('doc_tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_doc_tipo', models.CharField(blank=True, max_length=4, null=True)),
                ('desc_doc_tipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Documentos',
                'db_table': 'doc_tipo',
            },
        ),
        migrations.CreateModel(
            name='EmailClasif',
            fields=[
                ('email_clasif_id', models.AutoField(primary_key=True, serialize=False)),
                ('clasificacion', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Clasificación Email',
                'verbose_name_plural': 'Clasificaciones Email',
                'db_table': 'email_clasif',
            },
        ),
        migrations.CreateModel(
            name='EnteEducativo',
            fields=[
                ('ente_educ_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('representante', models.CharField(blank=True, max_length=100, null=True)),
                ('repr_telefono', models.CharField(blank=True, max_length=150, null=True)),
                ('repr_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rural', models.BooleanField(default=False)),
                ('referente', models.CharField(blank=True, max_length=100, null=True)),
                ('rural_plurigrado', models.BooleanField(default=False)),
                ('intercultural_bilingue', models.BooleanField(default=False)),
                ('cod_siisa', models.CharField(blank=True, max_length=20, null=True)),
                ('id_siisa', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Ente educativo',
                'verbose_name_plural': 'Entes Educativos',
                'db_table': 'ente_educativo',
                'permissions': (('view_enteeducativo', 'Can view Ente educativo'),),
            },
        ),
        migrations.CreateModel(
            name='EnteEducClasif',
            fields=[
                ('ente_clasif_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='desc_ente_clasif', max_length=50)),
            ],
            options={
                'verbose_name': 'Clasificación',
                'verbose_name_plural': 'Entes Educativos Clasificaciones',
                'db_table': 'ente_educ_clasif',
            },
        ),
        migrations.CreateModel(
            name='EnteEducGestion',
            fields=[
                ('ente_gestion_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='desc_ente_gestion', max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Gestión',
                'verbose_name_plural': 'Tipos de Gestión',
                'db_table': 'ente_educ_gestion',
            },
        ),
        migrations.CreateModel(
            name='EnteEducModalidad',
            fields=[
                ('ente_modalidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='desc_ente_modalidad', max_length=50)),
            ],
            options={
                'verbose_name': 'Ente Educativo Modalidad',
                'verbose_name_plural': 'Entes Educativos Modalidades',
                'db_table': 'ente_educ_modalidad',
            },
        ),
        migrations.CreateModel(
            name='EnteEducNivel',
            fields=[
                ('ente_nivel_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='cod_ente_nivel', max_length=4)),
                ('descripcion', models.CharField(db_column='desc_ente_nivel', max_length=50)),
            ],
            options={
                'verbose_name': 'Ente Educativo Nivel',
                'verbose_name_plural': 'Entes Educativos Niveles',
                'db_table': 'ente_educ_nivel',
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('lab_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Laboratorios',
                'db_table': 'laboratorio',
            },
        ),
        migrations.CreateModel(
            name='Lengua',
            fields=[
                ('lengua_id', models.AutoField(primary_key=True, serialize=False)),
                ('lengua_desc', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Lenguas',
                'db_table': 'lengua',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('loc_id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_loc', models.CharField(blank=True, max_length=3, null=True)),
                ('desc_loc', models.CharField(max_length=50)),
                ('cod_postal', models.IntegerField(blank=True, null=True)),
                ('cod_siisa', models.CharField(blank=True, max_length=20, null=True)),
                ('id_siisa', models.CharField(blank=True, max_length=20, null=True)),
                ('departamento', models.ForeignKey(db_column='dep_id', on_delete=django.db.models.deletion.CASCADE, related_name='localidades', to='core.Departamento')),
            ],
            options={
                'verbose_name_plural': 'Localidades',
                'db_table': 'localidad',
                'permissions': (('view_localidad', 'Can view localidad'),),
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('mun_id', models.AutoField(primary_key=True, serialize=False)),
                ('desc_mun', models.CharField(max_length=50)),
                ('localidad', models.ForeignKey(db_column='loc_id', on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='core.Localidad')),
            ],
            options={
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipio',
            },
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('obra_soc_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=6, null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('sigla', models.CharField(blank=True, max_length=30, null=True)),
                ('vigente', apps.core.db.metadata.BoolField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Obras sociales',
                'db_table': 'obra_social',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('pais_id', models.AutoField(primary_key=True, serialize=False)),
                ('desc_pais', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Paises',
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('prov_id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_prov', models.CharField(max_length=2)),
                ('desc_prov', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincia',
            },
        ),
        migrations.CreateModel(
            name='ScoreRCVClasif',
            fields=[
                ('score_clasif_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(blank=True, max_length=80, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'verbose_name_plural': 'Clasificación de score riesgo cardiovascular',
                'db_table': 'score_rcv_clasif',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('sexo_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('cod_sexo', models.CharField(max_length=1)),
                ('desc_sexo', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Sexos',
                'db_table': 'sexo',
            },
        ),
        migrations.CreateModel(
            name='TelClasif',
            fields=[
                ('tel_clasif_id', models.AutoField(primary_key=True, serialize=False)),
                ('clasificacion', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Clasificación Teléfono',
                'verbose_name_plural': 'Clasificaciones Teléfono',
                'db_table': 'tel_clasif',
            },
        ),
        migrations.CreateModel(
            name='TelTipo',
            fields=[
                ('tel_tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de Teléfono',
                'verbose_name_plural': 'Tipos de Teléfono',
                'db_table': 'tel_tipo',
            },
        ),
        migrations.CreateModel(
            name='Tribu',
            fields=[
                ('tribu_id', models.AutoField(primary_key=True, serialize=False)),
                ('tribu_nombre', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Tribus',
                'db_table': 'tribu',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('unid_med_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='unid_med', max_length=35)),
                ('abrev', models.CharField(blank=True, db_column='abrev', max_length=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unid_medida',
            },
        ),
        migrations.AddField(
            model_name='enteeducativo',
            name='clasif',
            field=models.ForeignKey(blank=True, db_column='clasif_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entes_educ', to='core.EnteEducClasif'),
        ),
        migrations.AddField(
            model_name='enteeducativo',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Localidad'),
        ),
        migrations.AddField(
            model_name='enteeducativo',
            name='modalidad',
            field=models.ForeignKey(blank=True, db_column='modalidad_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entes_educ', to='core.EnteEducModalidad'),
        ),
        migrations.AddField(
            model_name='enteeducativo',
            name='nivel',
            field=models.ForeignKey(blank=True, db_column='nivel_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entes_educ', to='core.EnteEducNivel'),
        ),
        migrations.AddField(
            model_name='enteeducativo',
            name='tipo_gestion',
            field=models.ForeignKey(blank=True, db_column='gestion_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entes_educ', to='core.EnteEducGestion'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='provincia',
            field=models.ForeignKey(db_column='prov_id', on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='core.Provincia'),
        ),
    ]
