
# -*- coding: utf-8 -*-

# Boolean
SI = 'S'
NO = 'N'

BOOLEAN = (
    (SI, 'Si'),
    (NO, 'No'),
)


# Mensajes - clasificaciones
MSG_CLASIF_MANUAL = 1
MSG_CLASIF_PROCESO = 2

# Mensajes
MSG001_FIRMA_BENEF = 1
MSG002_FIRMA_PROF = 2
MSG003_SELLO_PROF = 3
MSG004_AFI_NOT_MATCH = 4
MSG005_NO_INF_DOC = 5
MSG006_NO_INF_FECHA = 6
MSG007_DOC_DUPLICADO = 7
MSG008_AFI_NOT_FOUND = 8
MSG009_FALTA_ANEXO = 9
MSG010_PREST_NO_CONVENIO = 10
MSG011_PREST_CONV_PERIODO = 11
MSG012_PREST_PLANILLA_PERIODO = 12
MSG013_PREST_NO_NOMENCLADA = 13
MSG014_PREST_SIN_CODIGO = 14
MSG015_PREST_REPETIDA = 15
MSG016_BAJA_PADRON = 16
MSG017_PRE_AFI_CATEG = 17
MSG018_PRE_TASA_USO = 18
MSG019_PRE_EXCEDE_FECHA = 19
MSG020_REG_INCOMPLETO = 20
MSG021_TALLER_INCOMPLETO = 21
MSG022_PENDIENTE_LIQ = 22
MSG023_CALIDAD_OPORTUNIDAD = 23
MSG024_PREST_ANTES_INSCRIP = 24
MSG025_FALTA_REUNION_MPU22 = 25
MSG026_SUJETO_A_AUDITORIA = 26
MSG027_FALTA_DIAG = 27
MSG028_PREST_ANTES_FEC_NAC = 28
MSG029_TRZ_ERROR = 29


# Mensajes - Acciones
MSG_ACT_BAJA = 'B'
MSG_ACT_INFO = 'I'
MSG_ATC_WARN = 'W'

# Categoría de beneficiarios
CB_DISABLED   = 0
CB_EMBARAZADA = 1
CB_PUERPERA   = 2
CB_RECIEN_NAC = 3
CB_MENOR_6    = 4
CB_MENOR_20   = 5
CB_MAYOR_20   = 6

CB_GRUPO_MUJER = (CB_EMBARAZADA, CB_PUERPERA)
CB_GRUPO_CHICOS = (CB_RECIEN_NAC, CB_MENOR_6)

# Estado de planillas
PL_EST_PAPELERA = 0
PL_EST_ABIERTA = 1
PL_EST_CERRADA = 2
PL_EST_CANASTA = 3

# Estados de prestaciones en planilla (PE_ :Prestación Estado)
PE_PAPELERA = 0
PE_PEND_CONTROLAR = 1
PE_ACEPTADA = 2
PE_RECHAZADA = 3
PE_PEND_VALIDAR = 4

PE_VALIDADAS = (PE_ACEPTADA, PE_RECHAZADA,)

# Clase de documentos de identidad
DC_PROPIO = 1
DC_AJENO = 2  # Corresponde a ´A´ en sl SMI


# Tipos de documentos de identidad
DT_DNI = 1

# Bussines object
BO_EFECTOR = 1

# Unidades de Medida
UNID_MEDIDA_DEFAULT = 1  # Unidad

# Tipos de persona
PER_FISICA = 1
PER_JURIDICA = 2

# Derivadas de Persona
PER_BASE = 0
PER_PROFESIONAL = 1
PER_AFILIADO = 2

# Sexos
SEXO_MASCULINO = 1
SEXO_FEMENINO = 2
SEXO_EMPRESA = 3
SEXO_AMBOS = 0

# Edad para importar
EDAD_IMPORTAR = 1

# Codigos de condicion IVA
COND_IVA_EXENTO = 'EX'

# Tipos de Efector
EFE_TIPO_CAPS = 1
EFE_TIPO_CIC = 2
EFE_TIPO_DEP = 3
EFE_TIPO_HOSP = 4
EFE_TIPO_PRV = 5
EFE_TIPO_PSA = 6
EFE_TIPO_LAB = 7
EFE_TIPO_CCC = 8
EFE_TIPO_PSB = 9
EFE_TIPO_TRN = 10
EFE_TIPO_INST = 11


# Tipos de Agenda
AGENDA_TURNERO = 1
AGENDA_AGENDA = 2

# Estado de AgendaPeriodo
AGENDA_PERIODO_CERRADO = 1
AGENDA_PERIODO_VIGENTE = 2
AGENDA_PERIODO_ABIERTO = 3
